language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '8'
  - '10'
  - '12'
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "12"
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - "CXX=g++-4.8"
